// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// manifold_cpp
SEXP manifold_cpp(int n, int k, double vf_bound, const Eigen::VectorXd& lower, const Eigen::VectorXd& upper, Rcpp::Function coord_fun, Rcpp::Function pushforward_fun);
RcppExport SEXP _saman_manifold_cpp(SEXP nSEXP, SEXP kSEXP, SEXP vf_boundSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP coord_funSEXP, SEXP pushforward_funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type vf_bound(vf_boundSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type coord_fun(coord_funSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type pushforward_fun(pushforward_funSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_cpp(n, k, vf_bound, lower, upper, coord_fun, pushforward_fun));
    return rcpp_result_gen;
END_RCPP
}
// manifold_sample_cpp
Rcpp::NumericMatrix manifold_sample_cpp(SEXP M_ptr, int n_samples);
RcppExport SEXP _saman_manifold_sample_cpp(SEXP M_ptrSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_sample_cpp(M_ptr, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// manifold_metric_cpp
Eigen::MatrixXd manifold_metric_cpp(SEXP M_ptr, const Eigen::VectorXd& u);
RcppExport SEXP _saman_manifold_metric_cpp(SEXP M_ptrSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_metric_cpp(M_ptr, u));
    return rcpp_result_gen;
END_RCPP
}
// manifold_volume_form_cpp
double manifold_volume_form_cpp(SEXP M_ptr, const Eigen::VectorXd& u);
RcppExport SEXP _saman_manifold_volume_form_cpp(SEXP M_ptrSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_volume_form_cpp(M_ptr, u));
    return rcpp_result_gen;
END_RCPP
}
// manifold_coord_cpp
Eigen::VectorXd manifold_coord_cpp(SEXP M_ptr, const Eigen::VectorXd& u);
RcppExport SEXP _saman_manifold_coord_cpp(SEXP M_ptrSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_coord_cpp(M_ptr, u));
    return rcpp_result_gen;
END_RCPP
}
// manifold_pushforward_cpp
Eigen::MatrixXd manifold_pushforward_cpp(SEXP M_ptr, const Eigen::VectorXd& u);
RcppExport SEXP _saman_manifold_pushforward_cpp(SEXP M_ptrSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_pushforward_cpp(M_ptr, u));
    return rcpp_result_gen;
END_RCPP
}
// manifold_n_cpp
int manifold_n_cpp(SEXP M_ptr);
RcppExport SEXP _saman_manifold_n_cpp(SEXP M_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_n_cpp(M_ptr));
    return rcpp_result_gen;
END_RCPP
}
// manifold_k_cpp
int manifold_k_cpp(SEXP M_ptr);
RcppExport SEXP _saman_manifold_k_cpp(SEXP M_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_k_cpp(M_ptr));
    return rcpp_result_gen;
END_RCPP
}
// manifold_vf_bound_cpp
double manifold_vf_bound_cpp(SEXP M_ptr);
RcppExport SEXP _saman_manifold_vf_bound_cpp(SEXP M_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_ptr(M_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_vf_bound_cpp(M_ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_saman_manifold_cpp", (DL_FUNC) &_saman_manifold_cpp, 7},
    {"_saman_manifold_sample_cpp", (DL_FUNC) &_saman_manifold_sample_cpp, 2},
    {"_saman_manifold_metric_cpp", (DL_FUNC) &_saman_manifold_metric_cpp, 2},
    {"_saman_manifold_volume_form_cpp", (DL_FUNC) &_saman_manifold_volume_form_cpp, 2},
    {"_saman_manifold_coord_cpp", (DL_FUNC) &_saman_manifold_coord_cpp, 2},
    {"_saman_manifold_pushforward_cpp", (DL_FUNC) &_saman_manifold_pushforward_cpp, 2},
    {"_saman_manifold_n_cpp", (DL_FUNC) &_saman_manifold_n_cpp, 1},
    {"_saman_manifold_k_cpp", (DL_FUNC) &_saman_manifold_k_cpp, 1},
    {"_saman_manifold_vf_bound_cpp", (DL_FUNC) &_saman_manifold_vf_bound_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_saman(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
