# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

manifold_cpp <- function(n, k, vf_bound, lower, upper, coord_fun, pushforward_fun) {
    .Call(`_saman_manifold_cpp`, n, k, vf_bound, lower, upper, coord_fun, pushforward_fun)
}

manifold_sample_cpp <- function(M_ptr, n_samples) {
    .Call(`_saman_manifold_sample_cpp`, M_ptr, n_samples)
}

manifold_metric_cpp <- function(M_ptr, u) {
    .Call(`_saman_manifold_metric_cpp`, M_ptr, u)
}

manifold_volume_form_cpp <- function(M_ptr, u) {
    .Call(`_saman_manifold_volume_form_cpp`, M_ptr, u)
}

manifold_coord_cpp <- function(M_ptr, u) {
    .Call(`_saman_manifold_coord_cpp`, M_ptr, u)
}

manifold_pushforward_cpp <- function(M_ptr, u) {
    .Call(`_saman_manifold_pushforward_cpp`, M_ptr, u)
}

manifold_n_cpp <- function(M_ptr) {
    .Call(`_saman_manifold_n_cpp`, M_ptr)
}

manifold_k_cpp <- function(M_ptr) {
    .Call(`_saman_manifold_k_cpp`, M_ptr)
}

manifold_vf_bound_cpp <- function(M_ptr) {
    .Call(`_saman_manifold_vf_bound_cpp`, M_ptr)
}

